name: Slack Notification

on:
  push:
    branches: [main]
    paths:
      - 'DocCPublisherDemo/DocCPublisherDemo/*'

jobs:
  check-xcode-changes:
    runs-on: macos-latest
    env:
      FILES: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Get changed files
        id: changed_files
        run: |
          echo "Changed Files:"
          export FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '.swift' || true)
          echo "$FILES"

      - name: Get changes for each file
        id: get_changes
        run: |
          changes=""
          while IFS= read -r file; do
            class_name=$(basename "$file" .swift)
            changes+="\nChanges in $class_name:\n"
            changes+=$(git diff --unified=0 ${{ github.event.before }} ${{ github.sha }} "$file" | grep -A 2 "class $class_name" || true)
          done <<< "$FILES"

          echo "Changes:"
          echo "$changes"
          echo "::set-output name=changes::$changes"

      - name: Send message to Slack
        if: success()
        run: |
          changes=${{ steps.get_changes.outputs.changes }}

          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "Changes in Swift files:\n'"$changes"'",
            "channel": "#ios-demos",
            "username": "GitHub Actions"
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
