name: Swift File Changes Report

on:
  push:
    branches:
      - main

jobs:
  swift-file-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.x

    - name: Run Python Script
      run: |
        python detect_changes.py

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Post to Slack
      run: |
        curl -X POST -H 'Content-type: application/json' \
          --data '{"text": "'"$(cat ${{ github.workspace }}/path/to/changes-report.txt)"'"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
