name: CHECK FOR CHANGES

on:
  push:
    branches:
      - main

jobs:
  run-python-and-post-to-slack:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run Python Script
      id: run
      run: |
        report=$(python detect_changes.py)
        echo "::set-output name=report::$report"

    - name: Post to Slack
      if: ${{ success() }}
      run: |
        changes="${{ steps.run.outputs.report }}"
        curl -X POST -H 'Content-type: application/json' --data '{
          "text": "Changes in Swift files:\n'"$changes"'",
          "channel": "#ios-demos",
          "username": "GitHub Actions"
        }' ${{ secrets.SLACK_WEBHOOK_URL }}
