name: Notify Slack on Main Push

on:
  push:
    branches:
      - main

jobs:
  notify-slack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gitpython

      - name: Run Python script
        id: run_script
        run: python detect_changes.py

      - name: Send message to Slack
        if: success()
        run: |
          slack_message="${{ steps.run_script.outputs.stdout }}"
          slack_webhook_url="${{ secrets.SLACK_WEBHOOK_URL }}"

          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "'"$slack_message"'",
            "channel": "#ios-demo",
            "username": "GitHub Actions"
          }' "$slack_webhook_url"
