name: Check Xcode Changes

on:
  push:
    branches: [main]
    paths:
      - 'DocCPublisherDemo/DocCPublisherDemo/*'

jobs:
  check-xcode-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Xcode
      uses: actions/setup-xcode@v2
      with:
        xcode-version: '15.x' # Specify your desired Xcode version

    - name: Get changed files
      id: changed_files
      run: |
        echo "Changed Files:"
        echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '.swift' || true)"

    - name: Extract module name and class names
      id: extract_info
      run: |
        IFS=$'\n'
        files=(${{ steps.changed_files.outputs.files }})
        for file in "${files[@]}"; do
          module_name=$(echo $file | awk -F'/' '{print $2}')
          class_name=$(basename $file .swift)
          echo "Module Name: $module_name"
          echo "Class Name: $class_name"
          echo "::set-output name=module_name::$module_name"
          echo "::set-output name=class_name::$class_name"
        done

    - name: Get changes for each file
      id: get_changes
      run: |
        module_name=${{ steps.extract_info.outputs.module_name }}
        class_name=${{ steps.extract_info.outputs.class_name }}
        changes=$(git diff --unified=0 ${{ github.event.before }} ${{ github.sha }} ${{ steps.changed_files.outputs.files }} | grep -A 2 "class $class_name" || true)
        echo "Changes:"
        echo "$changes"

    - name: Send message to Slack
      if: success()
      uses: rtCamp/action-slack-notify@v2
      with:
        slack_webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
        channel: '#ios-demos'  # Replace 'your-channel-name' with the actual Slack channel name
        text: |
          "Changes to Module ${{ steps.extract_info.outputs.module_name }}"
          "Class Name: ${{ steps.extract_info.outputs.class_name }}.swift"
          "Changes -"
          "${{ steps.get_changes.outputs.changes }}"
